services:
  frontend:
    container_name: frontend
    build: ./frontend
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/.pnpm-store/:/app/.pnpm-store/
    ports:
      - 5173:5173
    environment:
      - PNPM_STORE_PATH=/app/.pnpm-store

  bff:
    container_name: bff
    build: ./bff
    tty: true
    volumes:
      - ./bff:/bff
    ports:
      - 3000:3000
  tag:
    container_name: tag
    build: ./backend/tag
    tty: true
    volumes:
      - ./backend/tag:/tag
    ports:
      - 4567:4567
  
