services:
  
    idp-migrate:
      build:
        context: .
        dockerfile: backend/idp/Dockerfile
        target: bin
        platforms:
          - linux/amd64
      image: idp:latest
      env_file:
        - .env
      entrypoint: ["/idp-service", "migrate"]
      platform: linux/amd64
      depends_on:
        db:
          condition: service_healthy
    idp-service:
      build:
        context: .
        dockerfile: backend/idp/Dockerfile
        target: bin
        platforms:
          - linux/amd64
      image: idp:latest
      ports:
        - "50051:50051"
        - "8082:8080"
      env_file:
        - .env
      entrypoint: ["/idp-service", "server"]
      healthcheck:
        test: ["CMD", "/grpc_health_probe", "-addr=:50051"]
        interval: 3s
        timeout: 3s
        retries: 20
      platform: linux/amd64
      depends_on:
        idp-migrate:
          condition: service_completed_successfully
        db:
          condition: service_healthy
    frontend:
      build: ./frontend
      tty: true
      volumes:
        - ./frontend:/app
        - /app/node_modules
        - ./frontend/.pnpm-store/:/app/.pnpm-store/
      ports:
        - 5173:5173
      environment:
        - PNPM_STORE_PATH=/app/.pnpm-store
      healthcheck:
        test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:5173/"]
        interval: 3s
        timeout: 3s
        retries: 40
    project-migrate:
      build:
        context: .
        dockerfile: backend/project/Dockerfile
      image: project:latest
      env_file:
        - .env
      entrypoint: ["./project-service", "migrate"]      
      platform: linux/amd64
      depends_on:
        db:
          condition: service_healthy
    project-service:
      build:
        context: .
        dockerfile: backend/project/Dockerfile
      image: project:latest
      ports:
        - "50053:50051"
      env_file:
        - .env
      entrypoint: ["./project-service", "server"]      
      healthcheck:
        test: ["CMD", "/grpc_health_probe", "-addr=:50051"]
        interval: 3s
        timeout: 3s
        retries: 20
      platform: linux/amd64
      depends_on:
        project-migrate:
          condition: service_completed_successfully
        db:
          condition: service_healthy
    db:
      image: postgres:17
      restart: unless-stopped
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DB}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
        interval: 2s
        timeout: 3s
        retries: 30
volumes:
  postgres-data:

