name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 手動実行のトリガーを追加

jobs:
  docker-build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, bff, project, user, session, board, task, column, role]
        include:
          - service: frontend
            context: ./frontend
          - service: bff
            context: ./bff
          - service: project
            context: ./backend/project
          - service: user
            context: ./backend/user
          - service: session
            context: ./backend/session
          - service: board
            context: ./backend/board
          - service: task
            context: ./backend/task
          - service: column
            context: ./backend/column
          - service: role
            context: ./backend/role
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push ${{ matrix.service }} Docker image
        uses: ./.github/actions/docker-build-push
        with:
          context: ${{ matrix.context }}
          image-name: ${{ matrix.service }}