# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tag.proto for package ''

require 'grpc'
require 'tag_pb'

module TagService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'TagService'

    rpc :GetTag, ::TagRequest, ::TagResponse
    rpc :CreateTag, ::Tag, ::TagResponse
    rpc :UpdateTag, ::Tag, ::TagResponse
    rpc :DeleteTag, ::TagRequest, ::TagResponse
  end

  Stub = Service.rpc_stub_class
end
