# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto

require 'google/protobuf'


descriptor_data = "\n\ttag.proto\"E\n\x03Tag\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ntext_color\x18\x03 \x01(\t\x12\x10\n\x08\x62g_color\x18\x04 \x01(\t\"\x18\n\nTagRequest\x12\n\n\x02id\x18\x01 \x01(\t\"@\n\x0bTagResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\x03tag\x18\x03 \x01(\x0b\x32\x04.Tag2\x9b\x01\n\nTagService\x12#\n\x06GetTag\x12\x0b.TagRequest\x1a\x0c.TagResponse\x12\x1f\n\tCreateTag\x12\x04.Tag\x1a\x0c.TagResponse\x12\x1f\n\tUpdateTag\x12\x04.Tag\x1a\x0c.TagResponse\x12&\n\tDeleteTag\x12\x0b.TagRequest\x1a\x0c.TagResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tag").msgclass
TagRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TagRequest").msgclass
TagResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TagResponse").msgclass
